dist: xenial
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
matrix:
  allow_failures:
    - php: nightly
install: composer install && composer require volantus/php-pigpio
script:
  - vendor/phpunit/phpunit/phpunit